import React, { useState } from "react";

import { supabase } from "../supabase-client";
import { useAuth } from "../AuthContext";
import { Player } from "../classes/Player";
import { Organizer } from "../classes/Organizer";
import { useNavigate } from "react-router-dom";
import { Account } from "../classes/Account";

function SignIn() {
  const [isSignUp, setIsSignUp] = useState(false);
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [name, setName] = useState("");
  const [isOrganizer, setIsOrganizer] = useState(false);
  const [leagueName, setLeagueName] = useState("");
  const { setAccount } = useAuth();

  const navigate = useNavigate();

  async function handleSubmit(e: React.FormEvent) {
    e.preventDefault();
    if (isSignUp) {
      //create account

      console.log("Signing Up");

      const { data: signUpData, error: signUpDataError } =
        await supabase.auth.signUp({ email, password }); //supabase auth
      if (signUpDataError) {
        console.error("Error signing up", signUpDataError.message);
        return;
      }

      let role = "player";
      if (isOrganizer) {
        role = "organizer";
      }

      const id = signUpData.user?.id;
      if (!id) {
        console.error("No auth user id returned");
        return;
      }
      const { data: account, error: accountError } = await supabase
        .from("Account")
        .insert([{ userId: id, email, name, role }])
        .select("userId")
        .single();
      if (accountError) {
        console.error("Error fetching user in sign up", accountError.message);
        return;
      }

      const userId = account.userId;

      const { data: raceNum, error: raceNumError } = await supabase //get race num
        .from("CurrentRaceNum")
        .select("currentRaceNum")
        .single();
      if (raceNumError) {
        console.error("Error fetching user in sign up", raceNumError.message);
        return;
      }

      if (isOrganizer) {
        await supabase.from("Organizer").insert([{ userId, leagueName }]);
        //leagueId is auto generated by supabase
      } else {
        //player
        await supabase.from("Player").insert([{ userId }]);
      }
      navigate("/");
      console.log("Sign up successful");
    } else {
      //login

      console.log("Signing in");
      const { data, error } = await supabase.auth.signInWithPassword({
        //use supabase for auth
        email,
        password,
      });

      if (error) {
        console.error("Error signing in", error.message);
        return;
      }

      const user = data.user; //stores user data

      const { data: profile, error: profileError } = await supabase //fetch account from supabase
        .from("Account")
        .select("*")
        .eq("userId", user.id)
        .single();
      if (profileError) {
        console.error("Error fetching profile:", profileError.message);
        return;
      }

      if (profile.role === "player") {
        const { data: player, error: playerError } = await supabase //fetch account from supabase
          .from("Player")
          .select("*")
          .eq("userId", user.id)
          .single();
        if (playerError) {
          console.error("Error fetching profile:", playerError.message);
          return;
        }
        setAccount(
          new Player(
            profile.userId,
            profile.email,
            profile.name,
            profile.role,
            player.leagueId,
            player.totalPoints,
            player.gainedPoints,
          ),
        );
      } else if (profile.role === "organizer") {
        const { data: organizer, error: organizerError } = await supabase
          .from("Organizer")
          .select("*")
          .eq("userId", profile.userId)
          .single();

        if (organizerError) {
          console.error("Error fetching organizer:", organizerError.message);
          return;
        }

        setAccount(
          new Organizer(
            organizer.leagueId,
            organizer.leagueName,
            profile.userId,
            profile.email,
            profile.name,
            profile.role,
          ),
        );
      }
      if (profile.role === "admin") {
        //admin
        setAccount(
          new Account(
            profile.userId,
            profile.email,
            profile.name,
            profile.role,
          ),
        );
      }
      navigate("/");
      console.log("Sign in successful");
    }
  }

  return (
    <div className="vh-100 d-flex justify-content-center align-items-center bg-secondary position-relative">
      <h4 className="position-absolute top-0 start-0 m-4 text-light">
        🏎️ F1 Predictions 🏎️
      </h4>
      <div
        className="card bg-dark text-light shadow p-4"
        style={{ width: "350px" }}
      >
        <h3 className="text-center mb-4">
          {isSignUp ? "Create Account" : "Sign In"}
        </h3>

        <form onSubmit={handleSubmit}>
          <div className="mb-3">
            <label className="form-label">Email</label>
            <input
              type="text"
              className="form-control"
              value={email}
              onChange={(e) => setEmail(e.target.value)}
              required
            />
          </div>

          <div className="mb-3">
            <label className="form-label">Password</label>
            <input
              type="password"
              className="form-control"
              value={password}
              onChange={(e) => setPassword(e.target.value)}
              required
            />
          </div>

          {isSignUp && (
            <div>
              <div className="mb-3">
                <label className="form-label">Name</label>
                <input
                  type="text"
                  className="form-control"
                  value={name}
                  onChange={(e) => setName(e.target.value)}
                  required
                />
              </div>

              <div className="form-check mb-3">
                {" "}
                <input
                  className="form-check-input"
                  type="checkbox"
                  checked={isOrganizer}
                  onChange={(e) => setIsOrganizer(e.target.checked)}
                  id="organizerCheck"
                />
                <label className="form-check-label" htmlFor="organizerCheck">
                  Register as Organizer
                </label>
              </div>
              {isOrganizer && (
                <div className="mb-3">
                  <label className="form-label">League Name</label>
                  <input
                    type="text"
                    className="form-control"
                    value={leagueName}
                    onChange={(e) => setLeagueName(e.target.value)}
                    required
                  />
                </div>
              )}
            </div>
          )}

          <button type="submit" className="btn btn-primary w-100">
            {isSignUp ? "Sign Up" : "Login"}
          </button>
        </form>

        <div className="text-center mt-3">
          {isSignUp ? "Already have an account?" : "Don't have an account?"}
          <button
            className="btn btn-link p-0 ms-1"
            onClick={() => setIsSignUp(!isSignUp)}
          >
            {isSignUp ? "Sign In" : "Sign Up"}
          </button>
        </div>
      </div>
    </div>
  );
}

export default SignIn;
